name: Frontend CI pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v3

      - name: Set up NodeJS environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: sets Timezone for iOS runner
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Europe/Berlin'
          timezoneMacos: 'Europe/Berlin'

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install package dependencies
        run: yarn install

      - name: Execute unit cases
        run: yarn test:unit
      - name: Execute dependency-cruiser cases
        run: yarn test:dependencies
