name: CI/CD

on:
  push:
    branches:
      # We can define multiple branches as well
      - master
  pull_request:
    branches:
      - master

jobs:
  TEST_ENV:
    # Defines the type of runner the job runs on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up NodeJS environment
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: sets Timezone for iOS runner
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: 'Europe/Berlin'
          timezoneMacos: 'Europe/Berlin'

      - name: Install package dependencies
        run: yarn install

      - name: Execute test cases
        run: yarn test
